### ISSUE TITLE
Provide the same folder structure as the MPL

### ISSUE THREAD

**Issue by ldionne** [brunocodutra/metal#1]
If the same structure as that of the MPL is used, then people could really just rename from `boost/mpl/...` to `boost/mpl2/...` in their includes. Also, one advantage of a backwards compatible MPL is the fact that one does not have to relearn new stuff. The plain directory structure of the old MPL was easy to grok and I think will be expected by users of this library. Just my 0.2.

**Comment by brunocodutra** [comment]
On one hand, MPL2 must somehow mimic MPL's original include structure in order for it to truly be _a modern drop in replacement for Boost.MPL_.

On the other hand, it seems consensual that MPL in fact consists of two orthogonal concepts, metafunctions and sequences, the latter depending on the former, but not conversely, so it seems most natural that each halve be split into its own subtree. Furthermore, with the advent of [C++ modules](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4047.pdf), each could be provided as a module of its own and I believe a segregated include tree should ease the adoption of this concept. In any case, I've been also fiddling with the idea of forking MPL2's metafunction halve into a library of its own right, called perhaps MPLambda, so it pretty much forces me to adopt the segregated structure no matter what.

Now how then will MPL2 serve as a drop in replacement for MPL if it doesn't mirror MPL's include structure? Well, it sure will! A proxy include tree under `mpl/` will be provided, which shall exactly mirror that of MPL and include MPL2's equivalents, taking care of any necessary adaptors. This way MPL2 may be given absolute flexibility, even to semantically divert from MPL if so necessary, while the proxy include tree is in charge of adapting each construct so as to guarantee MPL's original semantics. The idea is that any piece of code depending on MPL may instead use MPL2 without any modifications whatsoever, provided of course the compiler is able to handle MPL2.

**Comment by ldionne** [comment]
I think this should be closed, since it does not seem to apply anymore (not MPL2 anymore).

**Comment by brunocodutra** [comment]
Even though this enhancement, as you originally proposed, doesn't quite fit Metal as it is right now, the way I planned to tackle it might still apply. In fact it depends on what Metal evolves into and how closely it adheres to the MPL way by then, so I decided to leave this issue open till it becomes clear whether this wrapper for backwards compatibility to MPL makes any sense.

**Comment by ldionne** [comment]
Makes sense.

**Comment by brunocodutra** [comment]
I'll close this, since Metal has departed considerably from the MPL way and also because as of v0.7 the recommended way of consuming Metal is through the [standalone header](https://github.com/brunocodutra/metal/blob/standalone/metal.hpp), which renders the folder structure less meaningful in general.
