### ISSUE TITLE
`FACT_9` is erroneously defined as `FACT_7 * 9`

### ISSUE THREAD

**Issue by ecrypa** [brunocodutra/metal#104]
I expected `FACT_8 * 9`, but there could be some good reason for the current implementation. In that case, a comment would have helped me.

https://github.com/brunocodutra/metal/blob/ebda810ea65a4cce4349a61d266a8e61822bd5db/test/unit/include/test/numbers.hpp#L15

**Comment by brunocodutra** [comment]
Sharp eyes, this is definitely a typo.
