### ISSUE TITLE
Find a clever way to implement merge<> in terms of transform<>

### ISSUE THREAD

**Issue by brunocodutra** [brunocodutra/metal#13]
While linear recursion works, blowing up maximum recursion depth limits is not cool.

**Comment by brunocodutra** [comment]
Investigate whether fast tracking (#14) could make quicksort quicker than merge sort.

**Comment by porkybrain** [comment]
Bare in mind I'm by no means a quicksort expert. Sounds like an interesting idea, however if quicksort always picks a bad pivot element wouldn't that mean you would have to do N pivots. In my understanding pivots must be done recursively so this would have max recursion depth issues right? 

Fast tracked merge sort with a 16 and a 4 fast track you have in the worst case something like:

N/16 + N%16 in the main loop +

16*7 (missing 16x fast track every time) + (N - 16*16)/16

so for a 271 element list you have 16 + 15 main loop + 112 + 1 merge track so 144 recursions. After that you just add 2 recursions (one in main loop and one on merge track) for every extra 16 elements. I hope I'm not bullshitting here but a recursion depth of 256 should be reached at 1167 elements.

**Comment by brunocodutra** [comment]
Problem is, it's not easy to implement a fast tracked merge. Contrary to join, merge would require dozens of specializations, since its driven by pairwise evaluations of a generic predicate. So I guess it is out of question.

Quicksort on the other hand gracefully relies on partition, which in turn relies on copy_if, which finally relies on join. In the worst case it recurses N times partitioning the list minus one element at each step. If we make partition super  fast recursing just a couple of times, I believe it could be faster and recurse less than merge sort currently.

**Comment by porkybrain** [comment]
The brigand implementation is somewhere between a merge sort and an insertion sort. You basically rip off a chunk, sort it and then merge that with the sorted list which you got from the last recursion. This is fast track able because you can look ahead and skip over multiple elements if the look ahead is still smaller than the insert element.

I think there is still some optimization potential in the brigand sort if you were to implement multiple fast tracks and implement it with function overloading rather than templates.

**Comment by brunocodutra** [comment]
I must have a closer look into Bringand's sort. At a first glance it is still not clear to me what's going on, but it must be killer, because it seems to also have inspired Louis in boostorg/hana@96ab5a2b603bf9fa56f72f082a2efb2c08fd8327

**Comment by porkybrain** [comment]
Thinking about this again yesterday it looks like the strengths and weaknesses of the brigand sort and a quick sort are pretty complimentary. Brigand does well if the data is 'grouped' a bit so the fast tracks happen more often and is worst when everything is distributed pretty evenly. Quicksort (assuming taking the first element is the pivot) is the opposite, if a range is almost already sorted it can go up to N*(N/2) comparisons and linear recursion but if stuff is pretty randomly distributed it goes towards N*log(N) comparisons. 

Therefore a kind of hybrid where you sort a bit then split your sorted list and partition the rest of the input to match one of the two halves and then sort a bit more brigand style before splitting and partitioning again could be faster especially in worst case. Worst case is actually pretty important, If I were to advertise that Kvasir usually works on huge lists but we can only guarantee 200 elements its still a hard sell.

It is important to note that calling the template 'lambda' predicate is probably the most expensive operation in the sort. Its not like sorting run time stuff where comparisons are usually cheaper than copying stuff around and pivoting (swapping) is cheaper than inserting in the middle of a list and stuff like that. Also I would not expect things like branch prediction and cache locality etc. making 'pure' algorithms faster like is the case with runtime sorts. Therefore I think complex hybrid stuff is much more viable in this domain (although it does come at a readability/maintainability price though).  

I'm not sure if this applies but it should be noted that boost.MPL won the last popularity contest with no regard to either maintainability or readability (its probably one of the only pieces of code I would really like to understand but don't).

**Comment by brunocodutra** [comment]
> I'm not sure if this applies but it should be noted that boost.MPL won the last popularity contest with no regard to either maintainability or readability (its probably one of the only pieces of code I would really like to understand but don't).

Boost.MPL won it with no regard to performance nor low memory consumption either. On the other hand, it was born dead due to its unmaintainability, as it is still today what it was 10 years ago, bar a couple of rather minor bugfixes.

Making it hybrid does make sense when you think about it, but I tend to value much more an elegant implementation that only takes a couple of LOC to get the job done. I've been thinking about merge and I think I found a way to make it faster paced. The idea is to use remove_if at each step to compute the longest prefix of one of the lists for which the predicate is true when compared to the head of the other list, instead of prepending just the head at each step.

Haven't tested yet, but I think in the best case (already odered no matter the orientation) it would only take two steps no matter the size of the lists to merge.

**Comment by ldionne** [comment]
> (its probably one of the only pieces of code I would really like to understand but don't).

No, you don't. From my experience, the biggest part of the code there is just working around compiler bugs. The kind of fast tracking you guys implement in Brigand and the constexpr algorithms in Hana are much, much more interesting from a learning perspective. Just my .02

**Comment by brunocodutra** [comment]
I totally agree with Louis, it's just not worth it mentally evaluating all that preprocessor non-sense. There is really very little in Boost.MPL from the perspective of advanced metaprogramming techniques, as the bulk of it are dirty hacky workarounds for broken compilers.

**Comment by brunocodutra** [comment]
Closing this in favour of #17.
