### ISSUE TITLE
Investigate fast tracking for core algorithms

### ISSUE THREAD

**Issue by brunocodutra** [brunocodutra/metal#14]
The overall performance of Metal is particularly sensitive to core algorithms such as metal::join<>, which could see vast improvements if fast tracked linear recursed instead of tree-folded (edouarda/brigand#127).

**Comment by brunocodutra** [comment]
Perhaps @porkybrain could chime in?

**Comment by porkybrain** [comment]
Yes fast tracking join would be a major speed up. Looks like you can just take the brigand join.

**Comment by brunocodutra** [comment]
Not exactly, as Metal provides guarantees of SFINAE friendliness that Brigand does not, but the idea would the same, I'll give it a shot later today.

Have you experimented with other fast tracking constants? I gather x16 would bring it at most up to somewhere between 2048 and 4096 elements on clang without increasing recursion depth limits (which I believe to be around 256). Since we are doing it, we might as well go all the way to x32 or x64 or all three of them.

**Comment by porkybrain** [comment]
16 is a compromise between speed and me not wanting to type much ;) I think 4, 16 and 64 might not be a bad idea ;) Its really more of a code bloat vs. big list speed thing. If you have a whole lot of fast tracks it starts looking like boost.MPL again. It also has unit testing and readability implications.

For me so far it's been more about finding ways to fast track different algorithms (not everything is fast trackable). It may be worth making a METAL_FAST_TRACK_64 and a METAL_FAST_TRACK_64_TYPENAMES macro in order to increase readability. 

I like the idea of making a few core super fast tracked algorithms like join and then implementing all other algorithms on top of them.

**Comment by brunocodutra** [comment]
> It also has unit testing and readability implications
That's why I'm so wary of fast tracking.

I've looked for opportunities of fast tracking in Metal and so far I believe it would only be justifiable for join, which is the basis of several other algorithms, so I guess the clutter would be restricted to a single file.

**Comment by brunocodutra** [comment]
So, I experimented with fast tracking join for all powers of 2 up to 128.

Indeed I observed a tenfold improvement in performance, but only **if** joining `metal::list`s.
The gains for user defined lists aren't nearly as fantastic, because you can only make it so fast while still providing strong guarantees as Metal's. The difference arises because several algorithms take advantage of the fact `metal::list` is known to be variadic, always inheritable and to always define a nested `::type` pointing to itself, so most SFINAE checks may be skipped. I still need to experiment with it a little bit further, however, in order to assess to what degree this improvement in performance is reflected on higher level algorithms such as remove_if.

The improvement in performance is not free though, as I also observed a fivefold increase in memory consumption. For 7k pairs, the fast tracked version compromises over 2G RAM, while the current implementation requires around 400 MB, however the former takes around 10 seconds on my machine, while the latter takes around 2 minutes and 25 seconds to complete. That said, the user could always explicitly use `metal::reduce` for joining if the sheer performance of fast tracking isn't required, whereas if join itself relies on reduce internally, the user wouldn't have the alternative of a fast tracked version. 

Anyways, I guess I'll leave it resting on a branch till I decide whether all that clutter is really worth it.

**Comment by porkybrain** [comment]
its interesting that the fast tracked version uses more ram.

**Comment by brunocodutra** [comment]
It makes sense actually, for at each step of the linear recursion the compiler has to compute a new type that is dependent on hundreds if not thousands of template arguments. 

If you look at how `metal::reduce` is implemented, you will realize that at each step the only thing that varies are the last two template arguments that acount for the range. Besides, a tree-like recursion requires much fewer steps.

**Comment by porkybrain** [comment]
how are you measuring RAM usage? I have no good method right now.

**Comment by brunocodutra** [comment]
Very very poorly using a RAM monitor widget on my desktop, but it does give
you a rough idea for comparison purposes.

**Comment by brunocodutra** [comment]
moving this discussion to #41
