### ISSUE TITLE
Value type of true_/false_ is defined as boolean in documentation, but it is a number

### ISSUE THREAD

**Issue by UweJae** [brunocodutra/metal#144]
Maybe, this issue is placed wrong. It is an issue regarding the documentation. The type of `true_ `/`false_` in the documentation is described as boolean constant, but it is a number. The documentation for eg. `contains `mentions the return value correctly as `number`. But it forwards to `true_`/`false_`. So someone could assume, that `contains_result `in following code snipped is of type `bool`: `auto contains_result = metal::contains<list, element>::value`

**Comment by brunocodutra** [comment]
Thanks for taking the time to bring this to my attention, I've raised PR #145 to make it explicit in the documentation that `true_` and `false_` are Numbers.

**Comment by UweJae** [comment]
Thank you!
