### ISSUE TITLE
Collapsible panels are not intuitive - how to improve?

### ISSUE THREAD

**Issue by brunocodutra** [brunocodutra/metal#56]
It was pointed out that it is not immediately obvious that detailed documentation is available behind collapsible panels. 

It should be improved.

**Comment by Bagira80** [comment]
Try to do the same as Louis and you have done with [metaben.ch](http://metaben.ch/).
Add an icon to the panel which indicates that it is not just a static panel.

**Comment by brunocodutra** [comment]
That is not a bad idea at all and shouldn't be too hard to setup either, I'll give it a shot!

**Comment by brunocodutra** [comment]
@Bagira80 [what do you think](http://brunocodutra.github.io/metal/group__list.html)?

**Comment by Bagira80** [comment]
Way better! :+1: 
I would consider this issue solved.
