### ISSUE TITLE
Try supporting GCC 4.9 and 4.8 again

### ISSUE THREAD

**Issue by brunocodutra** [brunocodutra/metal#59]

**Comment by brunocodutra** [comment]
@pfultz2 GCC 4.9 was easy, I'll see what I can do for GCC 4.8 and earlier

**Comment by brunocodutra** [comment]
GCC 4.8 is also feasible, albeit trickier. GCC 4.7 on the other hand segfaults on metal::invoke, which is already carefully crafted to not crash MSVC, so I would really like to avoid touching it now.

Moving this discussion to PR #61

**Comment by pfultz2** [comment]
I did briefly look into this on gcc 4.7, but I don't think its possible without supporting compilers without template aliases, which looks to be pretty big task.

**Comment by brunocodutra** [comment]
Is there any specific requirement for Tick to support a compiler as old as GCC 4.6? 
AFAIK this is the default GCC version shipped with Ubuntu 12.04, which is so old, that despite being a LTS release, won't be supported anymore within a month, so it is increasingly unlikely that an average user would stumble across anything older than GCC 4.8.

**Comment by pfultz2** [comment]
This is true. Originally, I wrote Tick in 2014 so gcc 4.6 had a much longer lifetime support left. Also, gcc 4.6 is the last compiler to support Solaris 8, MIPS OpenBSD, IRIX 6.5, and Tru64 UNIX V5.1. I think these platforms are rarely used now(although, I have worked at places within the past few years that needed to support Solaris 8). I don't think its worth the effort for metal to support gcc 4.6.

**Comment by brunocodutra** [comment]
@pfultz2 I had to break the whole world, but finally I got GCC 4.7 to pass all unit tests.

**Comment by pfultz2** [comment]
Thats awesome.

**Comment by badair** [comment]
That's no small feat. How many ICEs did you hit? It would likely not take much more work to support the Intel compiler -- it's highly similar to GCC 4.7 in terms of C++11 compliance. You can request a license as an open source developer.

**Comment by brunocodutra** [comment]
> How many ICEs did you hit?

Don't even get me started. GCC 4.7 is particularly bad at SFINAEing out of nested alias template instantiations, which is a deal breaker for Metal that promotes SFINAE-friendliness above all. In the end the trick was to route intermediary steps through a forced SFINAE check in a function template context, quite a hassle TBH.

> It would likely not take much more work to support the Intel compiler

That sounds like a fun endeavour, I'll give it a shot this weekend. Thanks for the tip!

**Comment by brunocodutra** [comment]
@badair I've been trying ICC out and it looks like it is completely unable to SFINAE away from substitution errors in the instantiation of alias templates, which basically breaks *everything* in Metal. Are you aware of a reasonable workaround for this?

**Comment by badair** [comment]
@brunocodutra Depends what you mean by "reasonable". Without looking at the code, I assume you mean SFINAE within the template parameter list. IIRC, the Intel compiler does a decent job of implementing SFINAE in trailing return types. So if you can cleverly and successfully move your SFINAE there, it *might* be worth the code butchery.

Intel compiler is not great at standard compliance, but it does produce some highly optimized code. If Metal supported Intel, it could gain some users from the HPC world. Might be more trouble than it's worth, though.

**Comment by brunocodutra** [comment]
TBH I don't really know where exactly the problem lies, no single unit test passes because hard errors are produced where SFINAE should kick in, but I couldn't reproduce a minimal example.

I still want to try tailoring Metal to fit ICC, but I'll postpone it for now, as it doesn't seem to be an easy task.
