### ISSUE TITLE
partition is very slow for large-ish inputs

### ISSUE THREAD

**Issue by ldionne** [brunocodutra/metal#72]
While investigating the cause of timeouts on metaben.ch, I came across this (on GCC 4.9):

<img width="1255" alt="partition - metal" src="https://user-images.githubusercontent.com/700834/27262614-5fbab430-540f-11e7-8212-8939bd128e14.png">

This causes the total test time to take over 500 s, which contributes to the timing out of metaben.ch. I would suggest fixing this, or we will have to reduce the max size of the sample used for metal on metaben.ch.

**Comment by brunocodutra** [comment]
Thanks for reporting this. 

GCC versions prior to 5 require several sub-optimal workarounds to support Metal, so it's understandable that benchmarks can be very slow on them. 

Given results are sane on newer GCC versions, I don't think it's worth it to invest any effort on improving compilation times for such outdated versions, so I'll close this as wontfix and will open a PR on Metabench that disables Metal on GCC < 5 instead.

**Comment by ldionne** [comment]
Works for me!
