### ISSUE TITLE
::value and ::type aliases?

### ISSUE THREAD

**Issue by dpacbach** [brunocodutra/metal#83]
Would you accept a PR that adds aliases for ::value and ::type like the modern C++ standard library provides?  E.g.

`metal::same_v<t1, t2>`

instead of:

`metal::same<t1, t2>::value`

If I'm not mistaken these would be implemented with variable templates:

```
namespace metal {
  template<typename... Ts>
  auto same_v = same<Ts...>::value;
}
```

Though I believe this requires C++14 so perhaps they would only be enabled if the compilation supports at least that standard.

**Comment by pfultz2** [comment]
Since its an integral constant the constructor can be used to get a boolean(ie `bool b = same<t1, t2>{}`). The `_v` aliases seem quite unnecessary in C++, and are less powerful.

**Comment by brunocodutra** [comment]
> Though I believe this requires C++14 so perhaps they would only be enabled if the compilation supports at least that standard.

That's correct, one of the reasons this kind of alias is not provided out of the box is the extra complexity conditional compilation brings to testing, where we need to make sure both code paths are properly covered. In this particular case the costs seem to outweigh the gains, since pretty much the same thing can be expressed through the constructor and conversion operator, as pointed out by @pfultz2, which by the way also works in C++11.

Do you have a particular example of your use case?

**Comment by dpacbach** [comment]
Thanks -- I don't have any use case in particular, I just found that I like to use the _v and _t in the C++14/17 standard library because it makes code look cleaner :-)  But I can understand the difficulties that conditional compilation introduces, and could consider using the constructor (even though I don't like it as much and it is inconsistent with the modern C++ standards).  I will just close this.

**Comment by brunocodutra** [comment]
I now realize you mentioned aliases for `::type` too and that made me curious about what you might be referring to. Metal itself eagerly evaluates expressions, e.g. `metal::reverse<metal::list<t1, t2, t3>>` is itself an alias to `metal::list<t3, t2, t2>`, which means you don't ever need to be concerned about nested `::type`.

Now, if you need to interoperate with _lazy_ metafunction provided by third party libraries (such as Boost.MPL), have a look at [`metal::lazy`](http://brunocodutra.github.io/metal/group__lambda.html#ga00420618cd4689ece80838e596897d36), which returns a `metal::lambda` that implicitly evaluates the nested `::type`. Similarly, to interoperate with std `type_traits` you can use [`metal::trait`](http://brunocodutra.github.io/metal/group__lambda.html#gaa1d838da057cf0ff4c26bb2e66283fea), which returns a `metal::lambda` that implicitly converts its result to a `metal::number`. You might also want to check out [Migrating from Boost.MPL](http://brunocodutra.github.io/metal/index.html#MPL) for a more detailed discussion on this topic.

**Comment by dpacbach** [comment]
Oh ok that's nice to know, I wasn't aware of the eager evaluation.  In that case you are right that we don't need the ::type or _v.
