### ISSUE TITLE
List of bool template parameters

### ISSUE THREAD

**Issue by no-more-secrets** [brunocodutra/metal#90]
Is there a way using `metal` to hold a list of values (like `bool`s)?  In particular, I wanted something like this:

```static_assert( metal::all_true<true, true, true>::value, "" );```

I was hoping to put that inside an `enable_if` to check a list of conditions.  Is that possible?  Thanks

**Comment by brunocodutra** [comment]
You can achieve this in various ways and the most convenient/ergonomic may depend on the exact context.  If you could elaborate a little more I could help you find the best alternative, but basically what you're looking for is [`metal::and_`](http://brunocodutra.github.io/metal/group__number.html#ga73d6aa92adfac6cfacb2e935f5b37fb9):

```.cpp
template<bool... bs>
using all_true = metal::and_<metal::number<bs>...>;

static_assert( all_true<true, true, true>::value, "" );
```
You don't necessarily need to define your own helper though, you could achieve the same thing using metal alone:

```.cpp
static_assert( metal::apply<metal::lambda<metal::and_>, metal::numbers<true, true, true>>::value, "" );
```

You may also want to have a look at the [Parsing Raw Literals](http://brunocodutra.github.io/metal/index.html#parsing_raw_literals) example where you'll find some common patterns that may be similar to your use case.
