### ISSUE TITLE
Is `metal::arg` documented correctly (0-based vs. 1-based index)?

### ISSUE THREAD

**Issue by ecrypa** [brunocodutra/metal#94]
From the [explanation](https://github.com/brunocodutra/metal/blob/99e3857c5f069d553d4e5c07a33a0c7f53309578/include/metal/lambda/arg.hpp#L21) I expect a 0-based indexing, but the implementation uses 1-based indexing. Am I missing anything?

> ### Usage
> 
> For any non negative integral value `m`
> ```
> using result = metal::arg<m>;
> ```
> #### Returns: lambda
> #### Semantics:
> Equivalent to
> ```
> using result = metal::lambda<expr>;
> ```
> where `expr` is an Expression such that `expr<val_0, ..., val_m, ..., val_n-1>` yields `val_m`.
> ### Example
> ```
> IS_SAME(metal::invoke<metal::arg<1>, bool, char, long, float>, bool);
> IS_SAME(metal::invoke<metal::arg<2>, bool, char, long, float>, char);
> IS_SAME(metal::invoke<metal::arg<3>, bool, char, long, float>, long);
> IS_SAME(metal::invoke<metal::arg<4>, bool, char, long, float>, float);
> ```

**Comment by brunocodutra** [comment]
Great catch! Would appreciate your review on #95.
