### ISSUE TITLE
Why is `typename` used instead of `class`?

### ISSUE THREAD

**Issue by ecrypa** [brunocodutra/metal#96]
`template<class seq, template<class...> class expr>` and friends are more concise than `template<typename seq, template<typename...> class expr>`. The keyword `class` can help to reduce the character count, which simplifies skimming through the code. In addition, it prevents some line breaks that are otherwise required by the column limit.

Do you intentionally prefer `typename` for aesthetic reasons? Are there any compiler-compatibility issues in that direction?

**Comment by brunocodutra** [comment]
Just an old habit. I think my reasoning might have derived from the fact `class` is already used for template template parameters, but that's just silly, I'd rather have less line breaks.

We could probably just find&replace and let `clang-format` do the heavy lifting, there are only a handful of code sections that are hand formatted, so that's definitely manageable.

**Comment by ecrypa** [comment]
> We could probably just find&replace and let clang-format do the heavy lifting, there are only a handful of code sections that are hand formatted, so that's definitely manageable.

Two thoughts on this:

1. Special care is required because `typename` can also be used as a disambiguator. In that case, it must not be replaced by `class`.
2. I am not sure if such a small aesthetic improvement is worth the hassle. I was wondering if new code can use the new style. At some later point in time (when other reformattings are due), the `typename`-to-`class` changes could be integrated. That way, the manually formatted code sections need to be touched only once.

**Comment by brunocodutra** [comment]
> I was wondering if new code can use the new style.

The only concern I have about this, is whether it would show on docs as `typename` or `class`. While I'm fine with both variants to coexist in code, I'd prefer docs to be consistent in that regard to avoid confusion.

**Comment by ecrypa** [comment]
What about occurences of "typename" as a word in the doc?

https://github.com/brunocodutra/metal/blob/ebda810ea65a4cce4349a61d266a8e61822bd5db/include/metal/value/eval.hpp#L10

It can be renamed to "member typedef", "nested type alias", or it can be kept as it is because it refers the `typename` disambiguator:

https://github.com/brunocodutra/metal/blob/ebda810ea65a4cce4349a61d266a8e61822bd5db/include/metal/value/eval.hpp#L22

I am tempted to keep it as it is, but let us make sure we do not miss it.
